"""add is_open to area

Revision ID: 127ba89baefb
Revises: 48cbe6018104
Create Date: 2024-06-22 19:39:17.886955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '127ba89baefb'
down_revision: Union[str, None] = '48cbe6018104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('is_open', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('areas', 'is_open')
    # ### end Alembic commands ###
