"""remove user_type from schedules

Revision ID: 84357f380163
Revises: 127ba89baefb
Create Date: 2024-06-24 19:07:28.505726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84357f380163'
down_revision: Union[str, None] = '127ba89baefb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'user_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('user_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
