version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    command: /usr/src/app/entrypoint.sh
    environment:
      - DATABASE_HOSTNAME=
      - DATABASE_PORT=
      - DATABASE_PASSWORD=
      - DATABASE_NAME=
      - DATABASE_USERNAME=
      - SECRET_KEY=
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=
      - POSTGRES_PASSWORD=
    volumes:
      - postgres-db:/var/lib/postgresql/data 
volumes:
  postgres-db: