version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    command: /usr/src/app/entrypoint.sh
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=1104
      - DATABASE_NAME=agendaservidor
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=3aef523ec7cefc3ec190eac533559ca7276dc0130d6f19a639d285c879335b75
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=agendaservidor
      - POSTGRES_PASSWORD=1104
    volumes:
      - postgres-db:/var/lib/postgresql/data 
volumes:
  postgres-db: